/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef HelloService_H
#define HelloService_H

#include <thrift/TDispatchProcessor.h>
#include "hello_types.h"

namespace hello {

class HelloServiceIf {
 public:
  virtual ~HelloServiceIf() {}
  virtual void greeting(std::string& _return, const std::string& name, const int32_t age) = 0;
};

class HelloServiceIfFactory {
 public:
  typedef HelloServiceIf Handler;

  virtual ~HelloServiceIfFactory() {}

  virtual HelloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(HelloServiceIf* /* handler */) = 0;
};

class HelloServiceIfSingletonFactory : virtual public HelloServiceIfFactory {
 public:
  HelloServiceIfSingletonFactory(const boost::shared_ptr<HelloServiceIf>& iface) : iface_(iface) {}
  virtual ~HelloServiceIfSingletonFactory() {}

  virtual HelloServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(HelloServiceIf* /* handler */) {}

 protected:
  boost::shared_ptr<HelloServiceIf> iface_;
};

class HelloServiceNull : virtual public HelloServiceIf {
 public:
  virtual ~HelloServiceNull() {}
  void greeting(std::string& /* _return */, const std::string& /* name */, const int32_t /* age */) {
    return;
  }
};

typedef struct _HelloService_greeting_args__isset {
  _HelloService_greeting_args__isset() : name(false), age(false) {}
  bool name;
  bool age;
} _HelloService_greeting_args__isset;

class HelloService_greeting_args {
 public:

  HelloService_greeting_args() : name(), age(0) {
  }

  virtual ~HelloService_greeting_args() throw() {}

  std::string name;
  int32_t age;

  _HelloService_greeting_args__isset __isset;

  void __set_name(const std::string& val) {
    name = val;
  }

  void __set_age(const int32_t val) {
    age = val;
  }

  bool operator == (const HelloService_greeting_args & rhs) const
  {
    if (!(name == rhs.name))
      return false;
    if (!(age == rhs.age))
      return false;
    return true;
  }
  bool operator != (const HelloService_greeting_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloService_greeting_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class HelloService_greeting_pargs {
 public:


  virtual ~HelloService_greeting_pargs() throw() {}

  const std::string* name;
  const int32_t* age;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloService_greeting_result__isset {
  _HelloService_greeting_result__isset() : success(false) {}
  bool success;
} _HelloService_greeting_result__isset;

class HelloService_greeting_result {
 public:

  HelloService_greeting_result() : success() {
  }

  virtual ~HelloService_greeting_result() throw() {}

  std::string success;

  _HelloService_greeting_result__isset __isset;

  void __set_success(const std::string& val) {
    success = val;
  }

  bool operator == (const HelloService_greeting_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const HelloService_greeting_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const HelloService_greeting_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _HelloService_greeting_presult__isset {
  _HelloService_greeting_presult__isset() : success(false) {}
  bool success;
} _HelloService_greeting_presult__isset;

class HelloService_greeting_presult {
 public:


  virtual ~HelloService_greeting_presult() throw() {}

  std::string* success;

  _HelloService_greeting_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class HelloServiceClient : virtual public HelloServiceIf {
 public:
  HelloServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  HelloServiceClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void greeting(std::string& _return, const std::string& name, const int32_t age);
  void send_greeting(const std::string& name, const int32_t age);
  void recv_greeting(std::string& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class HelloServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<HelloServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (HelloServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_greeting(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  HelloServiceProcessor(boost::shared_ptr<HelloServiceIf> iface) :
    iface_(iface) {
    processMap_["greeting"] = &HelloServiceProcessor::process_greeting;
  }

  virtual ~HelloServiceProcessor() {}
};

class HelloServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  HelloServiceProcessorFactory(const ::boost::shared_ptr< HelloServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< HelloServiceIfFactory > handlerFactory_;
};

class HelloServiceMultiface : virtual public HelloServiceIf {
 public:
  HelloServiceMultiface(std::vector<boost::shared_ptr<HelloServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~HelloServiceMultiface() {}
 protected:
  std::vector<boost::shared_ptr<HelloServiceIf> > ifaces_;
  HelloServiceMultiface() {}
  void add(boost::shared_ptr<HelloServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void greeting(std::string& _return, const std::string& name, const int32_t age) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->greeting(_return, name, age);
    }
    ifaces_[i]->greeting(_return, name, age);
    return;
  }

};

} // namespace

#endif
