<%@ page contentType="text/xml; charset=euc-kr" %><?xml version="1.0" encoding="euc-kr" ?>
<root>
	<basic>
		<file>
			<name>basic-model-01.jpg</name> 
			<size>1500</size> 
			<type>jpg</type> 
			<path>/photo/basic-model-01.jpg</path>
			<url>/photo/basic-model-01.jpg</url>
		</file>
		<file>
			<name>basic-model-02.jpg</name> 
			<size>1502</size> 
			<type>jpg</type> 
			<path>/photo/basic-model-02.jpg</path>
			<url>/photo/basic-model-02.jpg</url>
		</file>
		<file>
			<name>basic-model-03.jpg</name> 
			<size>1503</size> 
			<type>jpg</type> 
			<path>/photo/basic-model-03.jpg</path>
			<url>/photo/basic-model-03.jpg</url>
		</file>
		<file>
			<name>basic-model-04.jpg</name> 
			<size>1504</size> 
			<type>jpg</type> 
			<path>/photo/basic-model-04.jpg</path>
			<url>/photo/basic-model-04.jpg</url>
		</file>
	</basic>
	<usp>
		<file>
			<name>usp-model-01.jpg</name> 
			<size>1500</size> 
			<type>jpg</type> 
			<path>/photo/usp-model-01.jpg</path>
			<url>/photo/usp-model-01.jpg</url>
		</file>
		<file>
			<name>usp-model-02.jpg</name> 
			<size>1502</size> 
			<type>jpg</type> 
			<path>/photo/usp-model-02.jpg</path>
			<url>/photo/usp-model-02.jpg</url>
		</file>
		<file>
			<name>usp-model-03.jpg</name> 
			<size>1503</size> 
			<type>jpg</type> 
			<path>/photo/usp-model-03.jpg</path>
			<url>/photo/usp-model-03.jpg</url>
		</file>
		<file>
			<name>usp-model-04.jpg</name> 
			<size>1504</size> 
			<type>jpg</type> 
			<path>/photo/usp-model-04.jpg</path>
			<url>/photo/usp-model-04.jpg</url>
		</file>
	</usp>
</root>
